export const QUESTION_ERROR_TYPES = {
  QUESTION_TEXT: 'QUESTION_TEXT',
  QUESTION_IMAGE: 'QUESTION_IMAGE',
  CHOICES_IS_TRUE: 'CHOICES_IS_TRUE',
  CHOICES_TEXT: 'CHOICES_TEXT',
  CHOICES_IMAGE: 'CHOICES_IMAGE',
}
